[package]
name = "prost-twirp"
version = "0.1.0"
authors = ["Chad Retz <chad.retz@gmail.com>"]

[features]
service-gen = ["prost-build"]

[dependencies]
futures = "0.1"
hyper = "0.11"
prost = "0.3"
prost-build = { version = "0.3", optional = true }
serde_json = "1.0"
